# Enable DEBUG for all Klava/XKlaim loggers
#org.slf4j.simpleLogger.log.klava=debug
#org.slf4j.simpleLogger.log.xklaim=debug

# Recommended: disable logging for the topology package, which is very verbose
org.slf4j.simpleLogger.log.org.mikado.imc.topology=off
org.slf4j.simpleLogger.log.org.mikado=off

# Alternatively, enable DEBUG globally (more verbose):
org.slf4j.simpleLogger.defaultLogLevel=debug

# Disable logging globally (not recommended):
#org.slf4j.simpleLogger.defaultLogLevel=off

# Recommended: include the timestamp in log output
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS